- name: levitron.zsh
  src: https://github.com/Levitron/ansible-role-zsh
- name: docker-compose-service
  src: https://github.com/Levitron/docker-compose-service
- src: gantsign.oh-my-zsh
- src: cloudalchemy.node-exporter