version: '3.7'

services:
  ingress:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /tmp/docker.sock
        read_only: yes
      #- /var/run/docker.sock:/tmp/docker.sock:ro
#      - type: bind
#        source: ./certs
#        target: /etc/nginx/certs

networks:
  default:
    external:
      name: nginx-proxy
