---
- name: restart {{ service_name }}
  become: yes
  service:
    name: '{{ service_name }}'
    state: restarted

- name: reload {{ service_name }}
  become: yes
  service:
    name: '{{ service_name }}'
    state: reloaded
