---

- hosts: all

  roles:
     - role: gantsign.golang
       golang_gopath: '$HOME/workspace-go'
  tasks:
    - name: clone fzf
      git:
        repo: https://github.com/junegunn/fzf.git
        dest: ~/.fzf
