version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    expose:
      - 8080
    command: --interval 600 --http-api-metrics --http-api-token TOP_SECRET
    networks:
      - reverse-proxy_default

networks:
  reverse-proxy_default:
    external: true
